### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by UnknownNull** [cooldogedev/TNTTag#13]
Sometimes TNT is placed on the ground and In other games that we are playing, the player's heal fills up quickly, which seems to be due to this plugin. Because this problem is solved by removing this plugin

**Comment by cooldogedev** [comment]
This plugin is designed to be ran as a server-per-game, so running it on a single instance with other plugins might cause some issues. As for the issues you mentioned, I couldn't reproduce any them, e.g. TNT placement is impossible because players are in adventure mode and it has nothing to do with player's regeneration.
